version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew clean build
      - run: ./gradlew test
      - run: ./gradlew jacocoTestReport
      - run: ./gradlew codacyUpload

      - store_test_results:
          paths:
            - build/reports
            - build/test-results/test

